### PR TITLE
Noso2k1 Seria A 2016-17

### PR DESCRIPTION
**Pull request by noso2k1**
Game list for Serie A 2016-17

### CODE REVIEW

**Comment by geraldb** [comment]
@noso2k1  Great. Thanks for adding the Seria A 2016-17 matches. Note: It looks great - however - if you try to parse / read the matches into your database it will NOT work - at least one date is needed per round.

**Comment by noso2k1** [comment]
@geraldb you're welcome. I added the match date, now.
I'm planning to keep the Serie A results updated

**Comment by geraldb** [comment]
@noso2k1  Fantastic. You're more than welcome. Let me know if you're interested in joining the GitHub org and I send you an invitation (via GitHub). If you accept you can edit the files in place (e.g. in your browser or push/commit directly without a pull request etc.).

**Comment by noso2k1** [comment]
@geraldb yes, that'd be great! Maybe you can allow me to edit only Serie A folder, if possible.

**Comment by geraldb** [comment]
@noso2k1  Welcome. Added you to the team - the github invitation (by email) is on its way. On the [peoples page](https://github.com/orgs/openfootball/people) you can make your membership public (or private is the default). Cheers.

**Pull request merged**
